update with renaming and prune lots of unused scripts (finally)

diff --git a/misc/mnt b/misc/mnt
--- a/misc/mnt
+++ b/misc/mnt
@@ -4,24 +4,24 @@
 
 [ "root" != "$USER" ] && exec sudo $0 "$@"
 
-# configuration:                                   /optional
+### config ###
+
+# configuration strings:                           /optional
 #                                                  v
-#       name: partuuid                             encrypted?  path
-crypt="crypt: 980bd86e-05ac-e14b-be7e-a78ca89a1325 (encrypted) /home/phat_sumo/crypt"
-storage="storage: 5e6eaeaa-6633-2d4a-b55a-e4ee9eb4a175 /home/phat_sumo/Storage"
-mobile="mobile: 3c952f4f-4568-bf43-974f-849ad192f932 /home/phat_sumo/mobile"
-work="work: 8820a3fc-8b68-2e4c-803c-d488e80f13a8 /home/phat_sumo/Documents/work"
-data="data: d85656c8-ab7a-cb41-b87e-10f5307f4e23 /home/phat_sumo/Documents/data"
+#       name: partuuid/uuid                        encrypted?  path
+tomb="tomb: 980bd86e-05ac-e14b-be7e-a78ca89a1325 (encrypted) /home/phat_sumo/tomb"
+crypt="crypt: 323ba667-0a9c-41a6-a20a-09445107b81d (encrypted) /home/phat_sumo/crypt"
+sarcophagus="sarcophagus: 30b8172e-0d63-4028-83f8-56420a135628 (encrypted) /home/phat_sumo/sarcophagus"
+miyoo="miyoo: 6035-81E2 /home/phat_sumo/miyoo"
 
-usage="usage: ${0##*/} [n] [cdmswh] or [cmsw]${0##*/}
-devices: 
+usage="usage: ${0##*/} [n] [cmsth]
+devices:
   c $crypt
-  d $data
-  m $mobile
-  s $storage
-  w $work
+  m $miyoo
+  s $sarcophagus
+  t $tomb
 
-commands: 
+commands:
   mnt DEVICE     mount specified device
   umnt DEVICE    unmount specified device
 
@@ -31,90 +31,110 @@ more:
   [cmsw]COMMAND    perform COMMAND and notify
   COMMAND h        print this menu"
 
-fail() { 
+### helper functions ###
 
-	echo ${0##*/}: 1>&2 "$*"
+fail() {
 
-	[ "$warn" ] && su phat_sumo -c "notify-send 'mnt' '$*'"
+  echo ${0##*/}:     "$*" 1>&2
 
-	exit 1; 
+  [ "$warn" ] && su phat_sumo -c "notify-send 'mnt' '$*'"
+
+  exit 1
 }
 
 try() {
-	out=$($* 2>&1)
-	err=$?
+  out=$($* 2>&1)
+  err=$?
 
-	[ $err -gt 0 ] && fail "$1 error $err: $out"
+  [ $err -gt 0 ] && fail "$1 error $err: $out"
 }
 
 notify() { su phat_sumo -c "notify-send -t 2000 'mnt' '$*'"; }
 
-open() { 
+open() {
 
-	partuuid=$(echo ${1##*: } | sed -e "s/ .*$//")
-	name="${1%%: *}"
-	path="${1##* }"
+  # extract useful parameters from the config string
+  partuuid=$(echo ${1##*: } | sed -e "s/ .*$//")
+  name="${1%%: *}"
+  path="${1##* }"
 
-	disk="/dev/disk/by-partuuid/$partuuid"
+  # to handle mounting fat filesystems, check if the length of the string
+  # is sized for a uuid name- otherwise, assume a partuuid name
+  case $(expr length $partuuid) in
+  9) disk="/dev/disk/by-uuid/$partuuid" ;;
+  *) disk="/dev/disk/by-partuuid/$partuuid" ;;
+  esac
 
-	[ ! -h "$disk" ] && fail "device $name not found"
+  [ ! -h "$disk" ] && fail "device $name not found"
 
-	# if device is encrypted, mount here
-	if [ ! "${1##*(encrypted)*}" ]; then
+  # if device is encrypted, mount here
+  if [ ! "${1##*(encrypted)*}" ]; then
 
-		try cryptsetup open /dev/disk/by-partuuid/$partuuid $name
+    try cryptsetup open /dev/disk/by-partuuid/$partuuid $name
 
-		disk="/dev/mapper/$name"
-	fi
+    disk="/dev/mapper/$name"
+  fi
 
-	mkdir $path; 
+  mkdir $path
 
-	try mount $disk $path
+  case $(expr length $partuuid) in
+  9)
+     disk="-t vfat $disk"
+                           path="$path -o rw,uid=1000,gid=1000"
+                                                                ;;
+  esac
+
+  try mount $disk $path
 }
 
-close() { 
+close() {
 
-	path="${1##* }"
-	name="${1%%: *}"
+  path="${1##* }"
+  name="${1%%: *}"
 
-	[ ! -d "$path" ] && fail "device $name not mounted"
+  [ ! -d "$path" ] && fail "device $name not mounted"
 
-	try umount $path
+  try umount $path
 
-	# if device is encrypted, close before continuing
-	[ ! "${1##*(encrypted)*}" ] && try cryptsetup close $name
+  # if device is encrypted, close before continuing
+  [ ! "${1##*(encrypted)*}" ] && try cryptsetup close $name
 
-	rm -rf $path
+  rm -rf $path
 }
 
-[ $# -gt 2 ] && fail "$usage"
+### main ###
 
-[ -z "$1" ] && warn="true"
+[ "$1" = "-n" ] && warn="true" && shift
 
-[ "$1" = "n" ] && warn="true" && shift
+while [ $# -gt 0 ]; do
 
-# use parameter or device code in prefix
-device_code=${1:-`echo ${0##*/} | sed -e "s/umnt$//" -e "s/mnt$//"`}
+  case "$1" in
+  c) device=$crypt ;;
+  m) device=$miyoo ;;
+  s) device=$sarcophagus ;;
+  t) device=$tomb ;;
+  h | "")
+          echo "$usage"
+          exit 0
+          ;;
+  ?) fail "error: device_code \"$1\" not recognized.\n\n$usage" ;;
+  esac
 
-case "$device_code" in
-	c) device=$crypt;;
-	d) device=$data;;
-	m) device=$mobile;;
-	s) device=$storage;;
-	w) device=$work;;
-	h|"") echo "$usage"; exit 0;;
-	?) fail "$usage";;
-esac
+  case "$0" in
+  *umnt)
+    close "$device"
+    echo "${device%%: *} closed successfully"
+    [ "$warn" ] && notify "${device%%: *} closed successfully"
+                                                              ;;
+  *mnt)
+    open "$device"
+    echo "${device%%: *} opened successfully"
+    [ "$warn" ] && notify "${device%%: *} opened successfully"
+                                                              ;;
+  esac
 
-case "$0" in
-	*umnt) 
-		close "$device";
-		echo "${device%%: *} closed successfully"
-		[ "$warn" ] && notify "${device%%: *} closed successfully";;
-	*mnt) 
-		open "$device";
-		echo "${device%%: *} opened successfully"
-		[ "$warn" ] && notify "${device%%: *} opened successfully";;
-esac
+  shift
+
+done
 
 exit 0
